# Generated by Django 4.2.3 on 2023-09-28 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presupuesto', models.IntegerField(default=500000000)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Fifa',
            fields=[
                ('nom', models.TextField(blank=True, db_column='Nom', null=True)),
                ('gen', models.IntegerField(blank=True, db_column='Gen', null=True)),
                ('potentiel', models.IntegerField(blank=True, db_column='Potentiel', null=True)),
                ('performance', models.FloatField(blank=True, db_column='Performance', null=True)),
                ('pays', models.TextField(blank=True, db_column='Pays', null=True)),
                ('club', models.TextField(blank=True, db_column='Club', null=True)),
                ('bonpied', models.TextField(blank=True, db_column='Bonpied', null=True)),
                ('mauvaispied', models.IntegerField(blank=True, db_column='Mauvaispied', null=True)),
                ('gestestechniques', models.IntegerField(blank=True, db_column='Gestestechniques', null=True)),
                ('taille', models.IntegerField(blank=True, db_column='Taille', null=True)),
                ('rendementoffensif', models.TextField(blank=True, db_column='Rendementoffensif', null=True)),
                ('rendementdefensif', models.TextField(blank=True, db_column='Rendementdefensif', null=True)),
                ('valeur', models.IntegerField(blank=True, db_column='Valeur', null=True)),
                ('salaire', models.TextField(blank=True, db_column='Salaire', null=True)),
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('centres', models.IntegerField(blank=True, db_column='Centres', null=True)),
                ('finition', models.IntegerField(blank=True, db_column='Finition', null=True)),
                ('precisiontete', models.IntegerField(blank=True, db_column='Precisiontete', null=True)),
                ('passescourtes', models.IntegerField(blank=True, db_column='Passescourtes', null=True)),
                ('volee', models.IntegerField(blank=True, db_column='Volee', null=True)),
                ('dribbles', models.IntegerField(blank=True, db_column='Dribbles', null=True)),
                ('effet', models.IntegerField(blank=True, db_column='Effet', null=True)),
                ('pcf', models.IntegerField(blank=True, db_column='PCF', null=True)),
                ('passeslongues', models.IntegerField(blank=True, db_column='Passeslongues', null=True)),
                ('controle', models.IntegerField(blank=True, db_column='Controle', null=True)),
                ('acceleration', models.IntegerField(blank=True, db_column='Acceleration', null=True)),
                ('vitesse', models.IntegerField(blank=True, db_column='Vitesse', null=True)),
                ('agilite', models.IntegerField(blank=True, db_column='Agilite', null=True)),
                ('reactivite', models.IntegerField(blank=True, db_column='Reactivite', null=True)),
                ('equilibre', models.IntegerField(blank=True, db_column='Equilibre', null=True)),
                ('puissancefrappe', models.IntegerField(blank=True, db_column='Puissancefrappe', null=True)),
                ('detente', models.IntegerField(blank=True, db_column='Detente', null=True)),
                ('endurance', models.IntegerField(blank=True, db_column='Endurance', null=True)),
                ('force', models.IntegerField(blank=True, db_column='Force', null=True)),
                ('tirsdeloin', models.IntegerField(blank=True, db_column='Tirsdeloin', null=True)),
                ('agressivite', models.IntegerField(blank=True, db_column='Agressivite', null=True)),
                ('interceptions', models.IntegerField(blank=True, db_column='Interceptions', null=True)),
                ('placement', models.IntegerField(blank=True, db_column='Placement', null=True)),
                ('vista', models.IntegerField(blank=True, db_column='Vista', null=True)),
                ('penalty', models.IntegerField(blank=True, db_column='Penalty', null=True)),
                ('calme', models.IntegerField(blank=True, db_column='Calme', null=True)),
                ('consciencedefensive', models.IntegerField(blank=True, db_column='Consciencedefensive', null=True)),
                ('tacledebout', models.IntegerField(blank=True, db_column='Tacledebout', null=True)),
                ('tacleglisse', models.IntegerField(blank=True, db_column='Tacleglisse', null=True)),
                ('plongeon', models.IntegerField(blank=True, db_column='Plongeon', null=True)),
                ('jeumain', models.IntegerField(blank=True, db_column='Jeumain', null=True)),
                ('jeupied', models.IntegerField(blank=True, db_column='Jeupied', null=True)),
                ('placement_1', models.IntegerField(blank=True, db_column='Placement.1', null=True)),
                ('reflexes', models.IntegerField(blank=True, db_column='Reflexes', null=True)),
            ],
            options={
                'verbose_name': 'jugador',
            },
        ),
        migrations.CreateModel(
            name='Plantel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EquipoApp.equipo', unique=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EquipoApp.fifa')),
            ],
        ),
    ]
