# Generated by Django 4.2.3 on 2023-09-29 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EquipoApp', '0002_alter_plantel_equipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantel',
            old_name='jugador',
            new_name='arquero',
        ),
        migrations.RemoveField(
            model_name='plantel',
            name='equipo',
        ),
    ]
