# Generated by Django 4.2.3 on 2023-09-29 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EquipoApp', '0003_rename_jugador_plantel_arquero_remove_plantel_equipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantel',
            old_name='arquero',
            new_name='jugador',
        ),
    ]
