# Generated by Django 4.2.3 on 2023-09-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EquipoApp', '0004_rename_arquero_plantel_jugador'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantel',
            name='posicion',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
