# Generated by Django 4.2.3 on 2023-09-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EquipoApp', '0005_plantel_posicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantel',
            name='general',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='plantel',
            name='nombre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plantel',
            name='pais',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plantel',
            name='valor',
            field=models.IntegerField(null=True),
        ),
    ]
