# Generated by Django 4.2.3 on 2023-09-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EquipoApp', '0006_plantel_general_plantel_nombre_plantel_pais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantel',
            name='posicion',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
