# Generated by Django 4.2.5 on 2023-10-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EquipoApp', '0009_clubes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubes',
            name='categoria',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
