# Generated by Django 4.2.5 on 2023-10-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EquipoApp', '0010_clubes_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=40)),
                ('gen', models.IntegerField()),
                ('cat', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='clubes',
            name='categoria',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
