# Generated by Django 4.2.5 on 2023-10-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EquipoApp', '0014_alter_clubes_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubes',
            name='categoria',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='cat',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='club',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='gen',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
