# Generated by Django 4.2.5 on 2023-10-05 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EquipoApp', '0016_puntos'),
    ]

    operations = [
    ]
