# Generated by Django 4.2.5 on 2023-10-05 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EquipoApp', '0017_auto_20231005_2037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Puntos',
        ),
        migrations.DeleteModel(
            name='Torneo',
        ),
    ]
