# Generated by Django 4.2.5 on 2023-10-05 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EquipoApp', '0018_delete_puntos_delete_torneo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(blank=True, max_length=40, null=True)),
                ('gen', models.IntegerField(blank=True, null=True)),
                ('cat', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_db', models.IntegerField()),
                ('categoria', models.CharField(max_length=10)),
                ('resultado_mio', models.IntegerField(null=True)),
                ('resultado_rival', models.IntegerField(null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EquipoApp.torneo')),
            ],
        ),
    ]
