# Generated by Django 4.2.5 on 2023-10-06 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EquipoApp', '0020_puntos_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='torneo',
            old_name='club',
            new_name='nombre',
        ),
    ]
