# Generated by Django 4.2.5 on 2023-10-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EquipoApp', '0021_rename_club_torneo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='categoria',
            field=models.CharField(default='E', max_length=10),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='presupuesto',
            field=models.IntegerField(default=50000000),
        ),
    ]
