# Generated by Django 4.2.5 on 2023-10-06 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EquipoApp', '0022_equipo_categoria_alter_equipo_presupuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plantel',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EquipoApp.equipo'),
        ),
    ]
